### ISSUE TITLE
dynamic text fields

### ISSUE THREAD

**Issue by d33pak-s1ngh** [mohammadalijf/UnderLineTextField#25]
i want to create underlinetextfields programatically for that what properties do i need to set on textfield object ?  i have created a following textbox for sample which looks fine but when i start typing the placeholder goes up and the space between placeholder and text is very less.

[sample Image](https://ibb.co/mm79q7)

````
  let firstNameTextField : UnderLineTextField = {
        let textField = UnderLineTextField()
        textField.placeholder = "First Name"
        textField.translatesAutoresizingMaskIntoConstraints = false
        
```
        textField.activeLineColor = UIColor.blue
        textField.activeLineWidth = 2
        textField.inactiveLineColor = .lightGray
        textField.inactiveLineWidth = 1
        textField.errorLineWidth = 1
        textField.warningLineWidth = 1
        textField.font = UIFont.systemFont(ofSize: 14)
        return textField
    }()`

what else i need to set ?

**Comment by mohammadalijf** [comment]
@d33pak-s1ngh did you set any extra constraint that may change height of the textfield?

**Comment by d33pak-s1ngh** [comment]
it is working fine since i have put the textfields inside the stackview which automatically manage height. thank you i have another issue. i will create new one.
