### ISSUE TITLE
validation on submit

### ISSUE THREAD

**Issue by d33pak-s1ngh** [mohammadalijf/UnderLineTextField#26]
i have a form for user profile where user can submit profile info to server. when user click on submit button , i want to check validation of text fields which is working fine when user edit textfield.

how i can achieve validation error for all the UnderlineTextField on submit button like you are doing after text edit event.

it will be very helpful if you can help. 
Thank you.

**Comment by mohammadalijf** [comment]
@d33pak-s1ngh you can tell underlinetextfield when validate user inputs by changing validationType property of each textfield

```swift
underLineTextField.validationType = .onCommit
```

the code above changes validation times to manual.
then you can use underLineTextField.validate() in you submit method to validate user's input.
