### ISSUE TITLE
UITextView Underline

### ISSUE THREAD

**Issue by d33pak-s1ngh** [mohammadalijf/UnderLineTextField#28]
hello @mohammadalijf  this project has been very helpful for me to underline textfields and managing validations thank you for such creative work.
i want to know is there any way to underline a UITextView control like we are doing with UITextFields if there is way please let me know it will be helpful.

**Comment by mohammadalijf** [comment]
hello @d33pak-s1ngh glad UnderlineTextField was helpful to you. UITextView is somehow more complicated than textfields. i will work on TextViews as well as textfields soon. but for now you can use TextView with a Label for placeholder and a uiview for line. it's a bit tricky cause you need handle states and transformation in your viewcontroller via textview's delegates.

**Comment by d33pak-s1ngh** [comment]
thank you for your reply,  will wait for your next release thank you.
