### ISSUE TITLE
Ability to adjust spacing amount between textFields

### ISSUE THREAD

**Issue by anthonycastelli** [mohammadalijf/UnderLineTextField#30]
I have a few of these placed inside of a UIStackView and the spacing between elements is pretty huge. It'd be nice if there was a way to customize this. The size of each textField appears to be about 90pts, and only half of that is used when the placeholder moves up.

**Comment by mohammadalijf** [comment]
hi,
half of the textfield is reserved for placeholder and text, the other half is reserved for error/warning label
