### ISSUE TITLE
Xcode 10, Swift 4.2, iOS 12 Update?

### ISSUE THREAD

**Issue by mohsinka** [mohammadalijf/UnderLineTextField#34]
Hi Mohammad Ali,

Thank you for this wonderful library. We are using it extensively in our code and would an update in the repository for these specifics: Xcode 10, Swift 4.2, iOS 12. We are ever so grateful to you for this kickass library 👍 

Best,
Mohsin

**Comment by mohammadalijf** [comment]
Hi Mohsin,
thank you for your support 🙏🏼
swift 4.2 for Xcode 10 is already merged with develop branch. i will release new version tomorrow.

Best,
Mohammad Ali
