### ISSUE TITLE
new feature needed

### ISSUE THREAD

**Issue by eldhoseelias** [mohammadalijf/UnderLineTextField#35]
How we can create a Text View ?

**Comment by mohammadalijf** [comment]
this is a custom [UITextField](https://developer.apple.com/documentation/uikit/uitextfield) and [UITextView](https://developer.apple.com/documentation/uikit/uitextview) is something completely different.

**Comment by eldhoseelias** [comment]
i know UITextField and UITextView are different.
What i suggests that, i need a new  functionality, that what all the custom functionalities you are added to UITextField, are  with UITextView.
ie, UITextView with underline and error labels
