### ISSUE TITLE
Can't use the code

### ISSUE THREAD

**Issue by ann330001** [mohammadalijf/UnderLineTextField#36]
I use Cocoapods to install the example code, but there are many errors about the frameworks. How can i do to solve this problem?

![2018-11-05 4 57 30](https://user-images.githubusercontent.com/44768034/47988148-671ba900-e11c-11e8-9125-0a5af42b5cca.png)

**Comment by mohammadalijf** [comment]
hi @ann330001 ,
can you provide me more detail like which Xcode version are you using and what swift version you are trying to build?

**Comment by ann330001** [comment]
Xcode is Version 9.2. I have tried the Swift 3.2 and Swift 4.0. They have the same problem.

**Comment by mohammadalijf** [comment]
current version `2.1.0` supports swift 4.2 on Xcode 10. if you want to use swift 4 you need to use version `2.0.6`
