### ISSUE TITLE
line spacing and placeholder overlap with input text 

### ISSUE THREAD

**Issue by pushpankq** [mohammadalijf/UnderLineTextField#41]
Hi 

I am facing the issue, sometimes it taking to much space with the line.
And sometimes placeholder text overlapping with input text. 

I have attached the screenshots.

![Screenshot 2019-08-07 at 5 07 08 PM](https://user-images.githubusercontent.com/14274827/62620574-4f858100-b937-11e9-80e3-0adb2904b315.png)
![Screenshot 2019-08-07 at 5 15 43 PM](https://user-images.githubusercontent.com/14274827/62620575-4f858100-b937-11e9-8386-46d9a579e518.png)

**Comment by mohammadalijf** [comment]
hi pushpankq,
which version are you using? which iOS Version? Which Xcode version are you building? did you add height constraints to textfield?

**Comment by mohammadalijf** [comment]
closed due to missing information and inactivity
