### ISSUE TITLE
App stops working when user runs app for iphone 11 Pro Max Simulator 

### ISSUE THREAD

**Issue by Kaustubh2018** [mohammadalijf/UnderLineTextField#43]
App stops working when user runs app for iphone 11 Pro Max Simulator 
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-03 at 11 04 53](https://user-images.githubusercontent.com/50164461/66101770-a624d980-e5cd-11e9-8ffb-548067d4bd21.png)

**Comment by mohammadalijf** [comment]
can you give me more specific error detail? i ran the example app and it worked

**Comment by Kaustubh2018** [comment]
Basically it just hang the simulator.. nothing happens when it become firstResponder..
NOTE:- When I ran it on physical device then it works as expected..

Please try it with  Xcode 11.0 iphone Pro Max simulaor

Thanks

**Comment by Kaustubh2018** [comment]
DO I need to add KeyboardObserver in each and every class where ever I am using UnderlineTextField ?????

Because in example it is added and .. if we remove that observer than it stucks the screen..

**Comment by mohammadalijf** [comment]
hey @Kaustubh2018  sorry for late reply.
no you don't need `KeyboardObserver` and it is irrelevant to `UnderLineTextField`. the `KeyboardObserver` only observe keyboard's frame changes and push scrollview's bottom so view would be visible. if you remove observer the keyboard will cover views in bottom.

**Comment by mohammadalijf** [comment]
@Kaustubh2018  about simulator freezing when a textfield become a firstRepsoner, i could'nt reproduce the same bug. i am currently building the example app with Xcode 11.1 (11A1027) on a mid 2014 macbook pro

**Comment by Kaustubh2018** [comment]
Hi, 

Following was happening with me ... and I got the solution from the last comment...This was not from your side...Thanks for helping...

https://forums.developer.apple.com/thread/122972 

Solution:

"Simulator -> Edit -> Automatically Sync Pasteboard" cancel selected.

"Hardware -> Restart"
